apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "discovery-mock.fullname" . }}-config"
data:
  appconfig.json: |
    {
      "app": {
        "service": {
          "identity": {{ .Values.service.serviceName | quote }}
        },
        "stubgenerator": {
          "host": "0.0.0.0",
          "port": {{ .Values.sidecar.port | quote }}
        }
      },
      "server": {
        "port": {{ .Values.service.containerPort | quote }}
      },
      "spring": {
        "data": {
          "mongodb": {
            "uri": {{ printf "mongodb://%s:%s@%s:%s/%s" .Values.mongodb.auth.username .Values.mongodb.auth.password (include "mongodb.fullname" .) .Values.mongodb.port .Values.mongodb.auth.database | quote }}
          }
        },
        "rabbitmq": {
          "host": {{ printf "%s.%s.svc.cluster.local" .Values.rabbitmq.host .Values.rabbitmq.namespace | quote }},
          "port": {{ .Values.rabbitmq.port | quote }},
          "username": {{ .Values.rabbitmq.auth.username | quote }},
          "password": {{ .Values.rabbitmq.auth.password | quote }}
        }
      }
    }