apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: health-rs
spec:
  replicas: 3

  selector:
    matchLabels:
      app: health

  template:
    metadata:
      name: health-check
      labels:
        app: health
    spec:
      containers:
        - name: health-app
          image: defimov/otus_lesson2:01
          ports:
            - containerPort: 80