apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "inventory.fullname" . }}-config"
data:
  url: {{ printf "jdbc:postgresql://%s:%s/%s" (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase | quote }}
  dbuser: {{ .Values.postgresql.postgresqlUsername | quote }}
  appconfig.json: |
    {
      "app": {
        "ext-service": {
          "discovery": {
            "host": {{ printf "%s.%s.svc.cluster.local" .Values.externalservices.discovery.host .Values.externalservices.discovery.namespace | quote }},
            "port": {{ .Values.externalservices.discovery.port | quote }}
          },
          "dev-lib": {
            "host": {{ printf "%s.%s.svc.cluster.local" .Values.externalservices.library.host .Values.externalservices.library.namespace | quote }},
            "port": {{ .Values.externalservices.library.port | quote }}
          }
        },
        "service": {
          "identity": {{ .Values.service.serviceName | quote }}
        }
      },
      "spring": {
        "datasource": {
          "url": {{ printf "jdbc:postgresql://%s:%s/%s" (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase | quote }},
          "username": {{ .Values.postgresql.postgresqlUsername | quote }},
          "password": {{ .Values.postgresql.postgresqlPassword | quote }}
        },
        "rabbitmq": {
          "host": {{ printf "%s.%s.svc.cluster.local" .Values.rabbitmq.host .Values.rabbitmq.namespace | quote }},
          "port": {{ .Values.rabbitmq.port | quote }},
          "username": {{ .Values.rabbitmq.auth.username | quote }},
          "password": {{ .Values.rabbitmq.auth.password | quote }}
        }
      },
      "server": {
        "port": {{ .Values.service.containerPort | quote }}
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "inventory.fullname" . }}-secret"
type: Opaque
data:
  DB_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | trimAll "\n" | quote }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: flyway-cm
  labels:
    name: flyway-cm
data:
  {{- (.Files.Glob "migration/**").AsConfig | nindent 2 }}