apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "app-chart.fullname" . }}-config"
data:
  appconfig.json: |
    {
      "server": {
        "port": {{ .Values.service.containerPort | quote }}
      },
      "spring": {
        "data": {
          "mongodb": {
            "uri": {{ printf "mongodb://%s:%s@%s/%s" .Values.mongodb.auth.username .Values.mongodb.auth.password (include "mongodb.fullname" .) .Values.mongodb.auth.database | quote }}
          }
        },
        "cache": {
          "type":
    {{- if .Values.cache.enabled -}}
      {{ "caffeine" | quote | indent 1 }}
    {{- else -}}
      {{ "none" | quote | indent 1 }}
    {{- end }},
          "caffeine": {
            "spec": "maximumSize={{ .Values.cache.maxSize }},expireAfterAccess={{ .Values.cache.expire }}"
          }
        }
      }
    }