apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  hostname: postgresdb
  dbname: postgres
  username: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  password: cXo=