apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db

spec:
  replicas: 1
  serviceName: postgresdb

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres-pod
          image: postgres:12.2
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: dbname
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
          volumeMounts:
            - name: postgredb
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          livenessProbe:
            exec:
              command:
                - bash
                - "-c"
                - |
                  export PGPASSWORD=$POSTGRES_PASSWORD; psql -U $POSTGRES_USER -c 'SELECT 1' $POSTGRES_DATABASE
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 10

  volumeClaimTemplates:
    - metadata:
        name: postgredb
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi