create table users
(
    id         int generated by default as identity primary key,
    user_name  VARCHAR(256) unique not null,
    first_name VARCHAR(64),
    last_name  VARCHAR(128),
    email      VARCHAR(128) unique not null,
    phone      VARCHAR(32)
);